name : Test , Build, and Deploy
on: push
jobs:
  # 1. test
  # 2. build
  # 3. Deploy -> 콘솔만 남김
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        # github repo 리눅스 명령어로 클론하고 뭐시기 하는 걸 누가 만들어 놓은거임
        # import 같은거임 ㅇㅇ
        uses: actions/checkout@v4

      - name: 모듈 설치하기
        run: npm install

      - name: 테스트 실행하기
        run: npm run test